/**
 * Koraki API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ApplicationCreateDataModel { 
    status?: ApplicationCreateDataModel.StatusEnum;
    applicationName: string;
    url: string;
}
export namespace ApplicationCreateDataModel {
    export type StatusEnum = 'Created' | 'Active' | 'Disabled' | 'DuePayment';
    export const StatusEnum = {
        Created: 'Created' as StatusEnum,
        Active: 'Active' as StatusEnum,
        Disabled: 'Disabled' as StatusEnum,
        DuePayment: 'DuePayment' as StatusEnum
    };
}
