/**
 * Koraki API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IntegrationConfig } from './integrationConfig';


export interface ApplicationIntegrationViewModel { 
    name?: string;
    description?: string;
    code?: string;
    status?: string;
    createdOn?: Date;
    configurations?: Array<IntegrationConfig>;
}
