/**
 * Koraki API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface NotificationCreateDataModel { 
    status?: NotificationCreateDataModel.StatusEnum;
    notificationText?: string;
    thumbnailUrl?: string;
    variables?: string;
    location?: string;
}
export namespace NotificationCreateDataModel {
    export type StatusEnum = 'Created' | 'Processing' | 'Ready' | 'Hidden' | 'Removed';
    export const StatusEnum = {
        Created: 'Created' as StatusEnum,
        Processing: 'Processing' as StatusEnum,
        Ready: 'Ready' as StatusEnum,
        Hidden: 'Hidden' as StatusEnum,
        Removed: 'Removed' as StatusEnum
    };
}
