/**
 * Koraki API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface NotificationPublicViewDataModel { 
    notificationText?: string;
    thumbnailUrl?: string;
    createdOnWord?: string;
    variables?: string;
    createdOn?: Date;
    type?: NotificationPublicViewDataModel.TypeEnum;
    id?: number;
}
export namespace NotificationPublicViewDataModel {
    export type TypeEnum = 'Normal' | 'AnalyticsLive' | 'AnalyticsCountry' | 'AnalyticsCity' | 'AnalyticsHour';
    export const TypeEnum = {
        Normal: 'Normal' as TypeEnum,
        AnalyticsLive: 'AnalyticsLive' as TypeEnum,
        AnalyticsCountry: 'AnalyticsCountry' as TypeEnum,
        AnalyticsCity: 'AnalyticsCity' as TypeEnum,
        AnalyticsHour: 'AnalyticsHour' as TypeEnum
    };
}
