/**
 * Koraki API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IntegrationsViewModel } from './integrationsViewModel';


export interface SubscriptionsDataViewModel { 
    plan?: string;
    planName?: string;
    cost?: number;
    nextBilling?: Date;
    trialEndsIn?: number;
    isTrialPeriod?: boolean;
    status?: string;
    integrations?: Array<IntegrationsViewModel>;
    permissons?: { [key: string]: string; };
}
