/**
 * Koraki API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SubscriptionCreateDataViewModel { 
    subscriptionCode: string;
    name: string;
    address: string;
    city?: string;
    state?: string;
    zip?: string;
    country?: string;
    cardId: string;
    token: string;
    last4: string;
    expYear: number;
    expMonth: number;
}
