export * from './ajax.service';
import { AjaxService } from './ajax.service';
export * from './analytics.service';
import { AnalyticsService } from './analytics.service';
export * from './applications.service';
import { ApplicationsService } from './applications.service';
export * from './facebook.service';
import { FacebookService } from './facebook.service';
export * from './mailChimp.service';
import { MailChimpService } from './mailChimp.service';
export * from './notifications.service';
import { NotificationsService } from './notifications.service';
export * from './privy.service';
import { PrivyService } from './privy.service';
export * from './subscriptions.service';
import { SubscriptionsService } from './subscriptions.service';
export * from './widget.service';
import { WidgetService } from './widget.service';
export const APIS = [AjaxService, AnalyticsService, ApplicationsService, FacebookService, MailChimpService, NotificationsService, PrivyService, SubscriptionsService, WidgetService];
