export * from './ajax.service';
import { AjaxService } from './ajax.service';
export * from './analytics.service';
import { AnalyticsService } from './analytics.service';
export * from './applications.service';
import { ApplicationsService } from './applications.service';
export * from './facebook.service';
import { FacebookService } from './facebook.service';
export * from './intercom.service';
import { IntercomService } from './intercom.service';
export * from './invoices.service';
import { InvoicesService } from './invoices.service';
export * from './mailChimp.service';
import { MailChimpService } from './mailChimp.service';
export * from './notifications.service';
import { NotificationsService } from './notifications.service';
export * from './payment.service';
import { PaymentService } from './payment.service';
export * from './privy.service';
import { PrivyService } from './privy.service';
export * from './shopify.service';
import { ShopifyService } from './shopify.service';
export * from './subscriptions.service';
import { SubscriptionsService } from './subscriptions.service';
export * from './twitter.service';
import { TwitterService } from './twitter.service';
export * from './widget.service';
import { WidgetService } from './widget.service';
export * from './wordpress.service';
import { WordpressService } from './wordpress.service';
export * from './zapier.service';
import { ZapierService } from './zapier.service';
export const APIS = [AjaxService, AnalyticsService, ApplicationsService, FacebookService, IntercomService, InvoicesService, MailChimpService, NotificationsService, PaymentService, PrivyService, ShopifyService, SubscriptionsService, TwitterService, WidgetService, WordpressService, ZapierService];
